# Generated by Django 5.2.4 on 2026-02-21 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
